name: "snyk test"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: snyk/actions/setup@master

      - name: Snyk Test
        run: snyk test --sarif-file-output=snyk-code.sarif.json
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3   # ✅ updated version
        with:
          sarif_file: snyk-code.sarif.json           # ✅ correct file name
