name: "Snyk Code Test"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - uses: snyk/actions/setup@master
        with:
          version: latest

      - name: Snyk Code Test
        run: |
          snyk code test --sarif-file-output=snyk-code.sarif.json || echo "Snyk failed"
          ls -l
          cat snyk-code.sarif.json || echo "SARIF not generated"
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SARIF results
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif.json
