name: "Snyk Dependency Test"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set up Snyk
        uses: snyk/actions/setup@master
        with:
          version: latest

      - name: Snyk Test (Dependencies)
        run: snyk test --sarif-file-output=snyk-deps.sarif.json || echo "Snyk failed"
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SARIF results
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-deps.sarif.json
