name: "snyk code test"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set up Snyk
        uses: snyk/actions/setup@master
        with:
          version: latest

      - name: Snyk Dependency Test (npm audit equivalent)
        run: snyk test --sarif > snyk-deps.sarif.json
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Code Test (Static Analysis)
        run: snyk code test --sarif > snyk-code.sarif.json
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif.json
